<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

| Term    |  Brief description   |  
| :--- | :-- |
| Subsetting   |  select a subset from lists or arrays  |  
| Indexing   |  select an element from lists or arrays  |   
| Slicing   |  selecting a range of elements from lists or arrays  |  
| Masking| select specific element(s) from arrays |

## Exercise 2

In [1]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
num_array = np_array_2d[:,0]
arr = num_array.astype(int)
arr%2
arr%2 == 1
print(sum(arr%2))
my_mask = (arr%2 == 1)
masked = np_array_2d[my_mask]
print(masked[:,1].tolist()) #cleaner presentation to get rid of "dtype"

5
['A', 'C', 'E', 'G', 'I']


## Exercise 3

In [24]:
np_array = np.array(
    [[66, 50, 57, -1, -1],
     [92, -1, 88, -1, -1],
     [75, -1, -1, 76, -1],
     [-1, 51, 87, -1, -1],
     [71, -1, 67, -1, 69]])
mask1 = np_array < 50
np_array[mask1]
mask2 = np_array > 50
np_array[mask2] = int(1)
mask3 = np_array == 50
np_array[mask3] = int(0)

print(np_array)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
